### ISSUE TITLE
'Coder Info' Pop up Issues

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#100]
_From @sdgun on October 21, 2014 0:29_

Description
-----------------------------------------------------------------
'Coder Info' Pop up Issues

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
In the Chat Room
Click on a User handle

Check the 'Coder Info' Pop up

Expected Result
-----------------------------------------------------------------
Must fix the Issue, 
- User name --> Username
- Rated events: --> Rated Matches:
- Last event --> Last Match

Actual Result
-----------------------------------------------------------------
'Coder Info' Pop up Issues

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7

Image
-----------------------------------------------------------------
![49](https://cloud.githubusercontent.com/assets/4592712/4711347/454ae8da-58b9-11e4-9a27-14a42f09ffa8.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201410 Release

_Copied from original issue: cloudspokes/arena-web#884_

**Comment by skyhit** [comment]
@mdesiderio  this is fixed in the backend.
