### ISSUE TITLE
'Logout Button' and Tool Top covered by the scroll bar

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#133]
_From @sdgun on October 20, 2014 19:16_

Description
-----------------------------------------------------------------
'Logout Button' and Tool Top covered by the scroll bar

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Hover over the Logout Button

Expected Result
-----------------------------------------------------------------
Must fix the Issue, 

Actual Result
-----------------------------------------------------------------
'Logout Button' and Tool Top covered by the scroll bar

Environment
-----------------------------------------------------------------
IE 11 in Windows 7

Image
-----------------------------------------------------------------
![8](https://cloud.githubusercontent.com/assets/4592712/4709298/4b29a3b0-589e-11e4-8ad8-d3919d1e0678.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201410 Release

_Copied from original issue: cloudspokes/arena-web#862_

**Comment by huangqun** [comment]
fixed for windows, but for Mac it's very hard to fix this, will see if the new scrollbar implementation will fix this.
