### ISSUE TITLE
[$75] When we filter a large list, blank area at the bottom appears in 'Challenges' Table

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#139]
_From @sdgun on September 23, 2014 14:33_

Description
-----------------------------------------------------------------
When we filter a large list, blank area at the bottom appears in 'Challenges' Table

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase, Enter code and compile them
In the Challenge phase, Do 45-50 Challenages (unsuccessfull/successfull) !!! Important
In the Summary page
Click 'View Details'
In the 'Challenges' Table
Click FLTER
Enter a handle (eg : sdgbh)
Click FILTER
Scroll down the list

Expected Result
-----------------------------------------------------------------
Must fix the Issue, 
- Must remove the blank area

Actual Result
-----------------------------------------------------------------
When we filter a large list, blank area at the bottom appears in 'Challenges' Table

Image
-----------------------------------------------------------------
![75](https://cloud.githubusercontent.com/assets/4592712/4375091/477acc8c-4339-11e4-9051-2b0484e4fbff.png)

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201409 Release

_Copied from original issue: cloudspokes/arena-web#779_

**Comment by GSTVAC** [comment]
Same as #137.

**Comment by huangqun** [comment]
fixed
