### ISSUE TITLE
[$75] Won't display the list when we collapse the list in 'Challenges' Table

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#140]
_From @sdgun on September 23, 2014 14:30_

Description
-----------------------------------------------------------------
Won't display the list when we collapse the list in 'Challenges' Table

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is Active
Click REGISTER
Wait till contest starts and room assignment completed
Click ENTER
In the Coding Phase, Enter code and compile them
In the Challenge phase, Do 45-50 Challenages (unsuccessfull/successfull) !!! Important
In the Summary page
Click 'View Details'
In the 'Challenges' Table
Click Expand
Sort by '#'
Scroll down to the bottom !!! important
Click Collapse

Expected Result
-----------------------------------------------------------------
Must fix the Issue, 
- Must display the list

Actual Result
-----------------------------------------------------------------
Won't display the list when we collapse the list in 'Challenges' Table

Image
-----------------------------------------------------------------
![74](https://cloud.githubusercontent.com/assets/4592712/4373657/2efd7bb0-432e-11e4-953e-effcf0d76abc.png)

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201409 Release

_Copied from original issue: cloudspokes/arena-web#778_

**Comment by GSTVAC** [comment]
working

**Comment by GSTVAC** [comment]
done

**Comment by huangqun** [comment]
fixed
