### ISSUE TITLE
[$50] No use of the 'Please wait while we retrieve coder information' message pop up

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#147]
_From @sdgun on September 22, 2014 15:35_

Description
-----------------------------------------------------------------
No use of the 'Please wait while we retrieve coder information' message pop up

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
In the Chat Area
Click on a user handle name
Check the First pop up that appears before the Coder Info pop up

Expected Result
-----------------------------------------------------------------
Must fix the Issue, 
- Must display more time
- Or must remove it

Actual Result
-----------------------------------------------------------------
No use of the 'Please wait while we retrieve coder information' message pop up

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7

Image
-----------------------------------------------------------------
![68](https://cloud.githubusercontent.com/assets/4592712/4358921/09bfc85a-426e-11e4-8345-43655ca86897.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201409 Release

_Copied from original issue: cloudspokes/arena-web#740_

**Comment by huangqun** [comment]
@mdesiderio is this what you were looking for? It shows this spinner before showing the pop up but I don't think it's what you meant. Should the pop up be shown instantly with a spinner on it until the info is loaded instead?

![image](https://cloud.githubusercontent.com/assets/6045894/5646806/e70ea064-96ba-11e4-9bf0-95721fdc3363.png)

**Comment by mdesiderio** [comment]
@huangqun I don't think this is a bad solution, but if we can show the popup immediately like you describe that would be best.

**Comment by phasebeta** [comment]
@huangqun ok, so it is going to be a blank coder info with overlay loader?

**Comment by huangqun** [comment]
@phasebeta I believe so, this is what @mdesiderio mentioned earlier in this issue: go directly to the second popup showing the spinner while it loads.

**Comment by huangqun** [comment]
@mdesiderio I'm not sure if this what expected, could you please check this screencast? http://screencast.com/t/ByUfTFdMW

**Comment by mdesiderio** [comment]
@huangqun I can accept this solution, I think it is fine.

**Comment by huangqun** [comment]
fixed
