### ISSUE TITLE
[$50] Arena doesn't open on IE10, Windows Server 2012

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#149]
_From @abhineet255 on September 22, 2014 8:40_

The arena opens on Chrome browser on the same machine. But not on IE10. It just shows a blank screen.

Screenshot attached
![ie10](https://cloud.githubusercontent.com/assets/8856556/4353518/1e707680-4234-11e4-8785-19451450c28b.png)

_Copied from original issue: cloudspokes/arena-web#731_

**Comment by huangqun** [comment]
fixed
