### ISSUE TITLE
[$75] Layout issue in the Test Panel in IE

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#151]
_From @sdgun on September 21, 2014 13:15_

Description
-----------------------------------------------------------------
Layout issue in the Test Panel in IE

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/#/a/home
Login via valid user
When the Registration Phase is ON
Click REGISTER
Wait till Coding phase starts
Click ENTER
Open a Problem
Enter a code 
Click Submit
Then Click the 'Test Panel'

Expected Result
-----------------------------------------------------------------
Must fix the Issue, 

- Must hide the Scroll bar in IE

Actual Result
-----------------------------------------------------------------
Layout issue in the Test Panel in IE

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 32.0.2 in Windows 7

Image
-----------------------------------------------------------------
![54](https://cloud.githubusercontent.com/assets/4592712/4348560/6425d51a-4191-11e4-8f2c-3a75b2a8f2f1.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201409 Release

_Copied from original issue: cloudspokes/arena-web#698_

**Comment by mdesiderio** [comment]
@phasebeta my local environment seems to be working fine right now, has this been fixed for you? Maybe you need a new VM?

@huangqun what is the status and how should we proceed with this issue?

**Comment by huangqun** [comment]
@mdesiderio I cannot reproduce this in my environment. So I think unless @phasebeta can still reproduce it, we can close it for now?

**Comment by mdesiderio** [comment]
Great, thanks!

I am closing it, if it is still an issue it will be reopened in the next QA cycle.

Thanks!
