### ISSUE TITLE
[$50] Coding Area: display vertical scroll bar to be according to layout used

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#168]
_From @onetliviunicolae on September 23, 2014 18:8_

----------------------------------------------
Environment
---------------------------------------------------------
Windows 7
Mozilla Firefox 32.0.2
Chrome 35.0.1916.114 dev-m
Internet Explorer 11.0.9600.17280
Safari 5.1.7

---------------------------------------------------------

Description
-----------------------------------------------

Access application link http://qa.arena.topcoder.com..

Use own credentials to login.

Select 14.09 Release QA SRM 20 - Room 2 which is in challenge phase.

Select and press View Details.

Press on any result(green numebers) available.

Use vertical browser scroll bar.
 
actual:
----------------------------------------------------------

in coding area section is displayed vertical scroll bar.

expected:
----------------------------------------------------------

display vertical scroll bar to be according to layout application.

see attachment!

![a_001](https://cloud.githubusercontent.com/assets/5114907/4377215/8f7e5a86-434c-11e4-8239-15072a033174.png)
![scroll-bar](https://cloud.githubusercontent.com/assets/5114907/4377217/943e7754-434c-11e4-9b4a-414fe7459da9.png)

_Copied from original issue: cloudspokes/arena-web#789_

**Comment by huangqun** [comment]
fixed for windows, but for Mac it's very hard to fix this, will see if the new scrollbar implementation will fix this.

**Comment by huangqun** [comment]
ignore my previous comment, it was for a different issue

**Comment by mdesiderio** [comment]
@huangqun this seems to be fixed, I am closing it, if not please reopen
