### ISSUE TITLE
[$25] capitalization should be consistent

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#178]
_From @winterflame on September 14, 2014 15:51_

mac 10.9.4, Chrome 35

1. login as heffan, change to Orange theme
2. enter proper data on each step, observe the spelling on the last screen

expected: capitalization should be consistent, should be “Coder per Room”, or “Registration start”

actual: see screenshot, there is “Registration Start” and “Coder per room”.

![qq20140914-11](https://cloud.githubusercontent.com/assets/4590317/4266322/73331164-3c7b-11e4-8cfb-563d76e5443a.jpg)

_Copied from original issue: cloudspokes/arena-web#530_

**Comment by mdesiderio** [comment]
@huangqun bug bounty.

Also please address the alignment of the assignment method.

Thanks!

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
