### ISSUE TITLE
text “Customized Room Assignment” should be changed

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#181]
_From @winterflame on September 14, 2014 15:31_

mac 10.9.4, Chrome 35

1. login as heffan, change to light theme
2. click Contest creation wizard
3. enter proper data on first and second screen
4. on the step 3 screen
5. observe

expected: text “Customized Room Assignment” should be changed to “Customize Room Assignment”

actual: see screenshot
![qq20140915-14](https://cloud.githubusercontent.com/assets/4590317/4266285/33c6c954-3c7a-11e4-8f4f-0a0d62e807ef.jpg)

_Copied from original issue: cloudspokes/arena-web#518_

**Comment by skyhit** [comment]
fixed myself.
