### ISSUE TITLE
[topcoder] should be [topcoder]’s

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#182]
_From @winterflame on September 14, 2014 15:40_

mac 10.9.4, Chrome 35

1. login as heffan, change to light theme
2. click Contest creation wizard
3. enter proper data on each step, on the step 3, observe the text

expected: [topcoder] should be [topcoder]’s for consistency

actual: see screenshot

![qq20140914-9](https://cloud.githubusercontent.com/assets/4590317/4266307/12193732-3c7b-11e4-952c-d5d3f77df421.jpg)

_Copied from original issue: cloudspokes/arena-web#523_

**Comment by skyhit** [comment]
fixed.
