### ISSUE TITLE
“Allowed Languages” expected on the last page

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#183]
_From @winterflame on September 14, 2014 15:37_

mac 10.9.4, Chrome 35

1. login as heffan, change to light theme
2. click Contest creation wizard
3. enter proper data on each step
4. then observe the summary page

expected: “Allowed Languages”, "Coders per room" expected on the last page

actual: see screenshots

![qq20140915-15](https://cloud.githubusercontent.com/assets/4590317/4266302/dc60844c-3c7a-11e4-95a3-39b78562ae32.jpg)

![qq20140915-16](https://cloud.githubusercontent.com/assets/4590317/4266303/e25d50dc-3c7a-11e4-8c26-7dbd3a55e73e.jpg)

![qq20140915-17](https://cloud.githubusercontent.com/assets/4590317/4266304/e820a60e-3c7a-11e4-9f41-abd375aab7f6.jpg)

_Copied from original issue: cloudspokes/arena-web#522_

**Comment by skyhit** [comment]
fixed already.
