### ISSUE TITLE
colon should be removed after “Status”/"Type"

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#186]
_From @winterflame on September 14, 2014 15:17_

mac 10.9.4, Chrome 35

1. login as heffan
2. click Contest creation wizard
3. enter proper data on each screen step by step, then observe the screen on the summary screen

expected: colon should be removed after “Status” and "Type"

actual: see screenshot

![qq20140915-10](https://cloud.githubusercontent.com/assets/4590317/4266246/bf471292-3c78-11e4-8959-886bc124565d.jpg)

_Copied from original issue: cloudspokes/arena-web#508_

**Comment by skyhit** [comment]
fixed.
