### ISSUE TITLE
[$30] layout issue on the summary screen

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#187]
_From @winterflame on September 14, 2014 15:15_

mac 10.9.4, Chrome 35

1. login as heffan
2. click Contest creation wizard
3. enter proper data on each screen, then observe the screen on the summary screen

expected: should have no layout issues

actual: see screenshot

![qq20140915-9](https://cloud.githubusercontent.com/assets/4590317/4266242/85e3f40c-3c78-11e4-8325-22a9a8a5993a.jpg)

_Copied from original issue: cloudspokes/arena-web#506_

**Comment by mdesiderio** [comment]
@huangqun similar to the other issue, bug bounty please.

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
