### ISSUE TITLE
there are underlines for the “>” and “<“

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#188]
_From @winterflame on September 14, 2014 15:6_

mac 10.9.4, Chrome 35

1. login as heffan
2. click Contest creation wizard
3. observe

expected: there should be no underlines under the two buttons

actual: see screenshot

![qq20140914-2](https://cloud.githubusercontent.com/assets/4590317/4266214/9c7ee0a6-3c77-11e4-8a2e-aac34b2e34b8.jpg)

_Copied from original issue: cloudspokes/arena-web#499_

**Comment by skyhit** [comment]
I can not reproduce this. so closing it.
