### ISSUE TITLE
[$30] 'You must provide an answer to the question' must 'You must provide an answers to the below questions'

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#191]
_From @sdgun on September 3, 2014 3:29_

Description
-----------------------------------------------------------------
'You must provide an answer to the question' must 'You must provide an answers to the below questions'

Steps
-----------------------------------------------------------------
Go to : http://arena.cloud.topcoder.com:3000
Login as lightspeed
Click Register
Check the Survey and Questions Support model
Don't answer to anything
Click 'I AGREE'

Check the Validation model title : 'You must provide an answer to the question'

Expected Result
-----------------------------------------------------------------
Must fix the Issue, 'You must provide an answers to the below questions'

Actual Result
-----------------------------------------------------------------
You must provide an answer to the question

Environment
-----------------------------------------------------------------
IE 9+, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 31 in Windows 7

Image
-----------------------------------------------------------------
![6](https://cloud.githubusercontent.com/assets/4592712/4129151/74a23c10-331a-11e4-9318-03c62018d691.png)

Bug Hunt
-----------------------------------------------------------------
Survey and Questions Support For Contest Registration

_Copied from original issue: cloudspokes/arena-web#444_

**Comment by mdesiderio** [comment]
@skyhit any updates on this?

**Comment by skyhit** [comment]
@mdesiderio can this be reproduced? I can not find any logic related to this problem in backend and frontend.

**Comment by huangqun** [comment]
@skyhit @mdesiderio  I added this one to bug bounty so we can get more members help test it.

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
fixed
