### ISSUE TITLE
[$30] [Light Theme] 'Rounds' Drop down Layout issue in the 'Leaderboard'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#206]
Description
-----------------------------------------------------------------
[Light Theme] 'Rounds' Drop down Layout issue in the 'Leaderboard'

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/
Login via Valid User
Go to Light Theme

Click 'Leaderboard'
Expand the 'Round' drop down

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must have bottom line of the drop down

Actual Result
-----------------------------------------------------------------
'Rounds' Drop down Layout issue in the 'Leaderboard'

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![3](https://cloud.githubusercontent.com/assets/4592712/5424112/04caaa92-8308-11e4-988c-37396b9af32b.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by huangqun** [comment]
This is still not working, I merged your changes and tested on both chrome and firefox:

![image](https://cloud.githubusercontent.com/assets/6045894/5604750/cf7cb708-940b-11e4-9825-8254bb852f24.png)

![snip20150104_2](https://cloud.githubusercontent.com/assets/6045894/5604752/d17475aa-940b-11e4-9643-f809cc2b740f.png)

**Comment by mdesiderio** [comment]
@huangqun this seems to be working in this latest version, can you please confirm and close the issue?

**Comment by huangqun** [comment]
@mdesiderio  works for me as well, closing it.
