### ISSUE TITLE
'Match Summary' Data is not aligned with the Column Headers

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#208]
Description
-----------------------------------------------------------------
'Match Summary' Data is not aligned with the Column Headers

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/
Login via Valid User
Go to Light Theme

When the Coding phase starts
Click ENTER
OR 
Click ENTER from the already completed Contest
Check the 'Match Summary' Table

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must align the Column headers and data

Actual Result
-----------------------------------------------------------------
'Match Summary' Data is not aligned with the Column Headers

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![6](https://cloud.githubusercontent.com/assets/4592712/5424130/c0b34e4e-8308-11e4-9855-9fa88738c5d6.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by mdesiderio** [comment]
@skyhit updates on this one?

**Comment by skyhit** [comment]
oh, sorry, I missed this, I will try to launch F2F challenges to get valid issues fixed.

**Comment by skyhit** [comment]
@mdesiderio  this is one thing we talked about to use Datatable, any opinion?

**Comment by mdesiderio** [comment]
Understood, so I will create a story for this sprint to migrate to datatable and close this so we can track internally
