### ISSUE TITLE
[$20] 'Filter' Expand/Collapse icon is not visible

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#209]
Description
-----------------------------------------------------------------
'Filter' Expand/Collapse icon is not visible

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/
Login via Valid User
Go to Light Theme

When the Coding phase starts
Click ENTER
In the 'Match Summary' Table
Click 'Challenges & Leaderboard'

Check the Filter icon in the 'Room  Leaderboard'

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must use another color for the 'Filter' Expand/Collapse icon

Actual Result
-----------------------------------------------------------------
'Filter' Expand/Collapse icon is not visible

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![7](https://cloud.githubusercontent.com/assets/4592712/5424131/c60a43a2-8308-11e4-9ba5-a3abb6193756.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by huangqun** [comment]
fixed
