### ISSUE TITLE
[$25] Code hides when user expand/collapse 'Coding Area'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#211]
Description
-----------------------------------------------------------------
Code hides when user expand/collapse 'Coding Area'

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/
Login via Valid User
Go to Light Theme

Click 'Practice Problems'
Click on a Problem
eg: ColorfulBuilding 

Enter a code (Don't Compile or Submit)
Click Expand
Now click Collapse

OR

Enter a code 
Click Compile
Click Test Panel
Click Run from one of the tests
Click Expand

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display the code

Actual Result
-----------------------------------------------------------------
Code hides when user expand/collapse 'Coding Area'

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![9](https://cloud.githubusercontent.com/assets/4592712/5424134/dbf458ec-8308-11e4-9271-b4f7a30cbf1d.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by huangqun** [comment]
Please re-test this one.

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
fixed
