### ISSUE TITLE
[$30] 'Test Report' Layout Issue

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#214]
Description
-----------------------------------------------------------------
'Test Report' Layout Issue in IE11

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/
Login via Valid User
Go to Light Theme

Click 'Practice Problems'
Click on a Problem
eg: GooseInZooDivOne

Enter a code
Click Compile 
Click Test Panel
Check All and click Run Test
Check the Test Case 4

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display the data in line as others in clolumn 2,3,4,5

Actual Result
-----------------------------------------------------------------
'Test Report' Layout Issue

Environment
-----------------------------------------------------------------
IE 11 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![12-ie](https://cloud.githubusercontent.com/assets/4592712/5424152/7a8bd804-8309-11e4-9e41-08271cd7861c.png)

In Chrome
![12-chrome](https://cloud.githubusercontent.com/assets/4592712/5424153/b2774adc-8309-11e4-98cc-2371b9313d3f.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by GSTVAC** [comment]
working

**Comment by GSTVAC** [comment]
done

**Comment by huangqun** [comment]
@GSTVAC how do you load that test problem into local arena and test it? I can only see TestProblem in test problems page.

**Comment by GSTVAC** [comment]
@huangqun Create a new contest and assign the GooseInZooDivOne problem to it. You'll be able to test it during the coding and challenge phases. If you still want to test it in the Practice Area, at the admin client go to Run contest > After contest > Insert practice rooms. The problem will show up in the Practice Problems area.

**Comment by huangqun** [comment]
fixed
