### ISSUE TITLE
[$30] [Orange Theme] Layout Issue when we display the Today Data in 'Match Plan'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#215]
Description
-----------------------------------------------------------------
[Orange Theme] Layout Issue when we display the Today Data in 'Match Plan'

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/
Login via Valid User
Go to Orange Theme

Click on Today in 'Match Plan'
Check There is a border covering the data

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must not display the Border
- Check with the Other dates
- Happening for all the themes

Actual Result
-----------------------------------------------------------------
Layout Issue when we display the Today Data in 'Match Plan'

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![13](https://cloud.githubusercontent.com/assets/4592712/5424138/17a846e6-8309-11e4-9247-a2d8951643c5.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
fixed
