### ISSUE TITLE
'Problem Area' Hides when we expand and then collapse

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#223]
Description
-----------------------------------------------------------------
'Problem Area' Hides when we expand and then collapse

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/
Login via Valid User
Go to Light Theme

Click 'Practice Problems'
Click on a Problem
eg: GooseInZooDivOne 
Enter Code
Click Compile and Submit
Click 'Practice Problems'
Click on the same Problem
eg: GooseInZooDivOne 

Then Expand the 'Problem Area' then collapse it

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display the Problem

Actual Result
-----------------------------------------------------------------
'Problem Area' Hides when we expand and then collapse

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![20](https://cloud.githubusercontent.com/assets/4592712/5424156/ce41f474-8309-11e4-87f0-bd09519f91e0.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by skyhit** [comment]
fixed.
