### ISSUE TITLE
[$30] [a4350000000CwONAA0,a4350000000CwOMAA0,a4350000000CwOLAA0,a4350000000CwkvAAC] Pop up saying "You cannot submit unless you have successfully compiled first." is not displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#296]
Description
-----------------------------------------------------------------
[a4350000000CwONAA0,a4350000000CwOMAA0,a4350000000CwOLAA0,a4350000000CwkvAAC] Pop up saying "You cannot submit unless you have successfully compiled first." is not displayed

Steps
-----------------------------------------------------------------
1. Hit url : https://qa.arena.topcoder.com/#/a/home
2. Login using your email or social sites
3. Register for a contest
4. Once the coding phase starts, click Enter
5. From the problems list given in right sidebar click the link "Unopened"
6. Once reading through the problem, click gear icon from coding area
7. Choose the language as VB.NET and click OK
8. Enter your code in coding area with a missing, say "}" or ";"
9. Click Compile
10. Now click Submit and click Yes on the confirmation window
11. Correct the code and then click Compile
12. Once successfull click Submit and click Yes on the confirmation window

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Pop up saying "You cannot submit unless you have successfully compiled first." should be displayed

Actual Result
-----------------------------------------------------------------
Pop up saying "You cannot submit unless you have successfully compiled first." is not displayed

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![26](https://cloud.githubusercontent.com/assets/4592712/5426764/8a12c3c6-8392-11e4-86d8-872365b8a37f.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
already fixed
