### ISSUE TITLE
[$50] Inserted Custom test cases displayed in other problems

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#298]
Description
-----------------------------------------------------------------
Inserted Custom test cases displayed in other problems

Steps
-----------------------------------------------------------------
Go to https://qa.arena.topcoder.com/#/a/home
Login as valid user
register for a contest
Click ENTER
Click on a Problem
Enter Code and compile it
Click Test panel
Add 3-4 Custom Test cases
Click Back to Match
Open another problem
Click Test Panel

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must not display on other problems

Actual Result
-----------------------------------------------------------------
Inserted Custom test cases displayed in other problems

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![27](https://cloud.githubusercontent.com/assets/4592712/5426850/4792c2b4-839a-11e4-8c3d-1aec74743f1c.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by huangqun** [comment]
fixed
