### ISSUE TITLE
[$40] Empty Test Case box displayed in the Test Panel

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#299]
Description
-----------------------------------------------------------------
Empty Test Case box displayed in the Test Panel

Steps
-----------------------------------------------------------------
Go to https://qa.arena.topcoder.com/#/a/home
Login as valid user
Register for a contest
Click ENTER
Click on a Problem (Eg:GooseInZooDivOne)
Enter Code and compile it
Click Test panel
Add 3-4 Custom Test cases
Click Back to Match
Open another problem (eg:RandomPaintingOnABoard)
Click Test Panel

Expand a newly added Test case
There must display only one parm, but it will display extra empty textbox

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display only related boxes

Actual Result
-----------------------------------------------------------------
Empty Test Case box displayed in the Test Panel

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![28](https://cloud.githubusercontent.com/assets/4592712/5426853/51a26908-839a-11e4-9c1e-685c99108142.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by crimmc** [comment]
Working on it...

**Comment by crimmc** [comment]
Unfortunately, I am unable to reproduce the issue.
I've tried with problems have the same and different number of parameters (e.g. "ColorfulBuilding" and "UndoHistory").
Before the last "Click Test Pane" there is a missing step "Enter code and click Compile".

Maybe a video would give me more details about how to reproduce the issue...

**Comment by huangqun** [comment]
I can't reproduce either, maybe already fixed.
