### ISSUE TITLE
[$25] [Common] Not able to scroll the list from the mouse

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#301]
Description
-----------------------------------------------------------------
Not able to scroll the list from the mouse

Steps
-----------------------------------------------------------------
Go to https://qa.arena.topcoder.com/#/a/home
Login as valid user
Register for a contest
Wait till the contest ends
Click ENTER
Click 'Challenges & Leaderboard'
Expand the 'Challenges'
Point the mouse to the table
Scroll using mouse (Wheel)

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must able to scroll using mouse

Actual Result
-----------------------------------------------------------------
Not able to scroll the list from the mouse

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![29](https://cloud.githubusercontent.com/assets/4592712/5427491/a124401c-83c4-11e4-9f95-d841812405fe.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by crimmc** [comment]
Working on it...

**Comment by crimmc** [comment]
Unfortunately, I am unable to reproduce the issue.
On my system a scrollbar is displayed as soon as the page is loaded and you are able to scroll the page using the mouse wheel.

Please let me know if I've missed anything...
![webarena-challengeeswithscrollbar](https://cloud.githubusercontent.com/assets/2634480/6092309/44ca7e74-aee1-11e4-9964-7e449ed043ac.png)

**Comment by GSTVAC** [comment]
This issue was fixed when ng-scrollbar was replaced by perfect-scrollbar.

**Comment by huangqun** [comment]
fixed
