### ISSUE TITLE
[$25] Hyperlink of the Appirio Logo in the Footer goes beyond the image

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#302]
Description
-----------------------------------------------------------------
Hyperlink of the Appirio Logo in the Footer goes beyond the image

Steps
-----------------------------------------------------------------
Go to https://qa.arena.topcoder.com/#/a/home
Login as valid user
Register for a contest
Wait till the contest ends
Click ENTER
Check the 'Appirio' Image in the footer

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must activate the hyperlink within the imgae area

Actual Result
-----------------------------------------------------------------
Hyperlink of the Appirio Logo in the Footer goes beyond the image

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![30](https://cloud.githubusercontent.com/assets/4592712/5427562/ad629802-83c8-11e4-9698-37e87157d035.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
