### ISSUE TITLE
[$25] Title difference in : Match Plan 

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#308]
Description
-----------------------------------------------------------------
Title difference in : Match Plan 

Steps
-----------------------------------------------------------------
Go to https://qa.arena.topcoder.com/#/a/home
Login as valid user
Check the Calender Title --> Match Plan

Click Match Plan
Check the Title --> Match Plan

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Title Must : Match Plan, after we click on 'View details'

Actual Result
-----------------------------------------------------------------
Title difference in : Match Plan 

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![32 1](https://cloud.githubusercontent.com/assets/4592712/5428053/6f441ab0-83db-11e4-9535-e6acd68080a2.png)
![32 2](https://cloud.githubusercontent.com/assets/4592712/5428054/6f6a287c-83db-11e4-9287-2a34d96156a1.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
fixed
