### ISSUE TITLE
[$20] duplicate points on the room page

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/arena-web#313]
Mac 10.10.1, chrome 35

1. register for an SRM
2. go into the room when the room assignment is completed
3. observe

expected: there should be no duplicate points on the page

actual: see screenshot

![qq20141215-2](https://cloud.githubusercontent.com/assets/4590317/5431715/53561d10-8469-11e4-8c3f-7c9b081b89d4.jpg)

**Comment by huangqun** [comment]
I think this is fixed now, but please re-test.

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
@shubhendusaurabh Actually were you able to reproduce this using the latest code from the branch? If you can could you let me know how? I tried a few times but haven't been able to reproduce this yet even before applying your fix. Thanks!

**Comment by shubhendusaurabh** [comment]
@huangqun i can reproduce this in Formal SRM

**Comment by huangqun** [comment]
fixed
