### ISSUE TITLE
[$30] Room In/Exit icon overlap with the scroll bar when there are more users

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#316]
Description
-----------------------------------------------------------------
Room In/Exit icon overlap with the scroll bar when there are more users

Steps
-----------------------------------------------------------------
Go to https://qa.arena.topcoder.com/#/a/home
Login as valid user
When the contest starts
Click ENTER

Check the handle name in the chat room
It will overlap with the scroll bar

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must not overlap

Actual Result
-----------------------------------------------------------------
Room In/Exit icon overlap with the scroll bar when there are more users

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![33](https://cloud.githubusercontent.com/assets/4592712/5431758/2ef07c54-8455-11e4-867d-058fba6a5395.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201412 Release

**Comment by huangqun** [comment]
fixed
