### ISSUE TITLE
"Request Timeout" when testing code in C# and VB.NET

### ISSUE THREAD

**Issue by macs054** [appirio-tech/arena-web#320]
ID [a4350000000CwOQAA0] [a4350000000CwksAAC]

Steps:
Login to Web Arena.
Register > Enter Contest.
Open problem 250.
Enter code and compile.
Click the Test Panel.
Select 2 test cases.
Click Run Test.

Actual Result:
Testing takes a long time and then Request Timeout message will appear.

Expected Result:
Test results window should appear.

![request timeout](https://cloud.githubusercontent.com/assets/1199534/5431832/e800d08e-846b-11e4-8769-692202874dca.png)

Sometimes there's a situation where Request Timeout will appear then suddenly the Test Result window will show. And also the Test result window will appear out of nowhere, I guess that's from the previous test and it took a long time to load.

Videos:
https://www.mediafire.com/?bbvbn4ow7kcfns3

**Comment by skyhit** [comment]
server side problem, closing this one
