### ISSUE TITLE
No active matches shown even when the match registration phase is on 

### ISSUE THREAD

**Issue by phasebeta** [appirio-tech/arena-web#382]
I used the latest revision in dev with PuTTy tunneling to Arena VM. I created the match with admin account (heffan), and tried to use user account to register on that match (name: 111). However, nothing is shown even though the match (name: 111) is already on its registration period. 

@huangqun @mdesiderio : Do you have this problem with Arena VM and local client?

![image](https://cloud.githubusercontent.com/assets/10266437/5546460/8295656e-8b75-11e4-952d-ca519afe1f95.png)

**Comment by skyhit** [comment]
you need to use the admin tool to activate it, otherwise, it will not be shown in the Active Matches widget.
