### ISSUE TITLE
[$25] Time Login and Logout button falls down from the right top corner in the SRM-Room view

### ISSUE THREAD

**Issue by cupidon4uk** [appirio-tech/arena-web#386]
Time, Coding time, Login, Messages logo and Logout button falls down in the SRM mode (after I entered the room).

![screenshot 2014-12-27 19 01 16](https://cloud.githubusercontent.com/assets/1242084/5561919/a8a9a914-8e03-11e4-850a-54a51c0a4cc1.png)
![screenshot 2014-12-27 19 01 18](https://cloud.githubusercontent.com/assets/1242084/5561920/a8af47ca-8e03-11e4-806a-e7a803318fa7.png)

**Comment by ananthhh** [comment]
Working on it

**Comment by huangqun** [comment]
@ananthhh how did you reproduce this? I can't seem to make it happen.

**Comment by ananthhh** [comment]
@huangqun You should shrink the screen when timer is visible. So you should be in coding phase and should be in contest or leaderboard page. This problem will occur when browser's window width is around 1200 to 1300px

**Comment by huangqun** [comment]
fixed
