### ISSUE TITLE
[$20] Tool Tip goes beyond the screen area in the 'Match Plan'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#430]
Description
-----------------------------------------------------------------
Tool Tip goes beyond the screen area in the 'Match Plan'

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Match Plan'
Click Grid View
Hover over January 22 etc...

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must expand the tool tip to downwards

Actual Result
-----------------------------------------------------------------
Tool Tip goes beyond the screen area in the 'Match Plan'

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![3](https://cloud.githubusercontent.com/assets/4592712/5886544/331c237e-a3cb-11e4-8a6b-2d84e7a32b06.png)
![3 1](https://cloud.githubusercontent.com/assets/4592712/5886545/3348c2da-a3cb-11e4-957f-093c55b47883.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
