### ISSUE TITLE
[$30] Coder Info not displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#431]
Description
-----------------------------------------------------------------
Coder Info not displayed

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Chat Area'

Click on coder's name
For the first time it won't display

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display the code info

Actual Result
-----------------------------------------------------------------
Coder Info not displayed

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![4](https://cloud.githubusercontent.com/assets/4592712/5870166/554d5a5a-a2ed-11e4-8a0f-0ad0c3b1444e.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by skyhit** [comment]
is it a common problem for all?

**Comment by sdgun** [comment]
@skyhit If you click for the first time, the answer is yes.

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
fixed
