### ISSUE TITLE
[$20] Chat Settings arrow Overlap with the icon

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#432]
Description
-----------------------------------------------------------------
Chat Settings arrow Overlap with the icon

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the Chat Area
Click on Settings

Chat Settings arrow Overlap with the icon

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must not overlap each other

Actual Result
-----------------------------------------------------------------
Chat Settings arrow Overlap with the icon

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![5](https://cloud.githubusercontent.com/assets/4592712/5870176/9e1902fc-a2ed-11e4-892d-ac20ba60f6a8.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
