### ISSUE TITLE
[$25] [Light Theme] Two lines in the bottom of the table in 'Practice Problems'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#433]
Description
-----------------------------------------------------------------
[Light Theme] Two lines in the bottom of the table in 'Practice Problems'

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
Go to 'Practice Problems'
Scroll down

Check the bottom line of the table

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must have only one line

Actual Result
-----------------------------------------------------------------
Two lines in the bottom of the table in 'Practice Problems'

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![8](https://cloud.githubusercontent.com/assets/4592712/5870224/67c59dc2-a2ee-11e4-9708-fe521a598829.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
