### ISSUE TITLE
[$25] [Light Theme] 'Loading...' animation is not clear in 'Practice Problems'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#434]
Description
-----------------------------------------------------------------
[Light Theme] 'Loading...' animation is not clear in 'Practice Problems'

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
Go to 'Practice Problems'
Scroll down

Go to another page
Check the 'Loading ...' Animation

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Text must visible

Actual Result
-----------------------------------------------------------------
'Loading...' animation is not clear in 'Practice Problems'

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![10](https://cloud.githubusercontent.com/assets/4592712/5870239/d41ba0fc-a2ee-11e4-9246-783b34ad81dd.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
@shubhendusaurabh in light theme the loading text is still not quite visible, fix this and we should be good.

**Comment by shubhendusaurabh** [comment]
@huangqun let me know if this looks good
![loading](https://cloud.githubusercontent.com/assets/1818387/6056271/4466b456-ad34-11e4-9b5c-115ef7895de8.png)

**Comment by huangqun** [comment]
@shubhendusaurabh  Can we use black text like in the orange theme? Just to make it consistent.

**Comment by shubhendusaurabh** [comment]
![load](https://cloud.githubusercontent.com/assets/1818387/6056381/18bc6416-ad36-11e4-9152-f0682449cdc2.png)

**Comment by huangqun** [comment]
This is good.

**Comment by huangqun** [comment]
fixed
