### ISSUE TITLE
[$25] [Light Theme and Orange Theme] Tool tip arrow color issue

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#436]
Description
-----------------------------------------------------------------
[Light Theme and Orange Theme] Tool tip arrow color issue

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
Go to 'Match Schedule'
Hover over the date marked with orange

Check the arrow

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Arrow color must match with the tool tip color
- Orange Theme --> Orange, Light Theme --> Light blue

Actual Result
-----------------------------------------------------------------
Tool tip arrow color issue

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![12](https://cloud.githubusercontent.com/assets/4592712/5870254/72850b3e-a2ef-11e4-9ba2-3b889892eb28.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
