### ISSUE TITLE
[$25] 'Match Summary' Table layout issue

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#437]
Description
-----------------------------------------------------------------
'Match Summary' Table layout issue

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Click ENTER from completed Match or In 'System Test Phase'

Check the 'Match Summary' table

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must align the data with the table headers

Actual Result
-----------------------------------------------------------------
'Match Summary' Table layout issue

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![13](https://cloud.githubusercontent.com/assets/4592712/5870375/1def3fba-a2f2-11e4-861f-778917f560fb.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by shubhendusaurabh** [comment]
not reproducible after fixing duplicate points issue

**Comment by huangqun** [comment]
fixed
