### ISSUE TITLE
Chat Settings: Sound [ON] won't work

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#438]
Description
-----------------------------------------------------------------
Chat Settings: Sound [ON] won't work

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Click ENTER

In the Char Area
click Settings
Sound --> ON
Enter some chats

OR

Select 'Reply to' or 'Whisper' and then select a user and enter chat
It won't play the sound

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must play a sound

Actual Result
-----------------------------------------------------------------
Chat Settings: Sound [ON] won't work

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Video
-----------------------------------------------------------------
https://drive.google.com/open?id=0B2TRwlgOU4zmbmhIVHF6RlNiTzQ&authuser=0

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by skyhit** [comment]
the video is improper,and the user getting reply or whisper should play the sound.
