### ISSUE TITLE
[$30] Chat Settings: History [ON][OFF] won't do nothing

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#439]
Description
-----------------------------------------------------------------
Chat Settings: History [ON][OFF] won't do nothing

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Click ENTER

In the Char Area
click Settings
History --> ON
Enter some chats
Log off from the current user
login again via the previous user
Check the History

Expected Result
-----------------------------------------------------------------
Must fix the Issue.

Actual Result
-----------------------------------------------------------------
Chat Settings: History [ON][OFF] won't do nothing

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![15](https://cloud.githubusercontent.com/assets/4592712/5870378/3d4ff4a8-a2f2-11e4-8809-74fdf91b09b2.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
@huangqun chat history setting is for current session only and data is stored in localstorage not in database. upon logging out all data associated with the user is cleared. messages persist if you close browser and open again, as long as you don't log out

**Comment by huangqun** [comment]
ok, makes sense. Mark this as fixed
