### ISSUE TITLE
[$25] When scrolling, messages pop up scrolls with the screen

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#440]
Description
-----------------------------------------------------------------
When scrolling, messages pop up scrolls with the screen

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Click ENTER

Click Messages
When the pop up is there 
scroll the screen up/down using mouse scroller

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display in fixed position

Actual Result
-----------------------------------------------------------------
When scrolling, messages pop up scrolls with the screen

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Video
-----------------------------------------------------------------
https://drive.google.com/open?id=0B2TRwlgOU4zmbmhIVHF6RlNiTzQ&authuser=0

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
@huangqun don't think this is an valid issue. Since position is being calculated  dynamically in javascript there will be some time lag.

**Comment by huangqun** [comment]
I agree, this shouldn't be a valid issue
