### ISSUE TITLE
[$25] 'Default language: Java' is not displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#441]
Description
-----------------------------------------------------------------
'Default language: Java' is not displayed

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Users (xxx)' section
Expand it
Click on a username that have MM details also
eg: ikatanic

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display the 'Default language: Java' 

Actual Result
-----------------------------------------------------------------
'Default language: Java' is not displayed

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![6 1](https://cloud.githubusercontent.com/assets/4592712/5870343/7e0d4f5a-a2f1-11e4-90db-08f51b1fedb8.png)
![6](https://cloud.githubusercontent.com/assets/4592712/5870344/7e49739a-a2f1-11e4-8589-10ebc339e860.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by skyhit** [comment]
some info seems hiding.

**Comment by shubhendusaurabh** [comment]
@huangqun can't reproduce with dev users

**Comment by huangqun** [comment]
@shubhendusaurabh I think this is similar to https://github.com/appirio-tech/arena-web/issues/478

@skyhit I have the same question here, is there any way we can add more info to test handles we are using in our VM?

**Comment by GSTVAC** [comment]
Same as https://github.com/appirio-tech/arena-web/issues/478#issuecomment-73788348.

**Comment by huangqun** [comment]
fixed but credit goes to @shubhendusaurabh  for reporting it as the first user
