### ISSUE TITLE
[$25] Match Registration pop up is too close to the top

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#442]
Description
-----------------------------------------------------------------
Match Registration pop up is too close to the top

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Click REGISTER

Check the pop up

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must have some gap from the top

Actual Result
-----------------------------------------------------------------
Match Registration pop up is too close to the top

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![17](https://cloud.githubusercontent.com/assets/4592712/5870443/61d2dd12-a2f3-11e4-947d-6ce801acce81.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
