### ISSUE TITLE
Vertical/Horizontal arrange icon won't do anything in 'Practice Problems'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#444]
Description
-----------------------------------------------------------------
Vertical/Horizontal arrange icon won't do anything in 'Practice Problems'

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Practice Problems'
Click 'ABCPath'

Click Vertical/Horizontal arrange icon

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- icon must work

Actual Result
-----------------------------------------------------------------
Vertical/Horizontal arrange icon won't do anything in 'Practice Problems'

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![19](https://cloud.githubusercontent.com/assets/4592712/5870565/80da26fe-a2f6-11e4-86a5-31ac63be276d.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by polkovnikov-ph** [comment]
@sdgun Could you describe how did you managed to open Practice in Web Arena?

**Comment by sdgun** [comment]
@polkovnikov-ph, After login to the http://arena.topcoder.com/, I clicked on the 'Practice Problems' link in the Menu. It will load the Practice Problems without any errors, Just followed the normal procedure.

**Comment by polkovnikov-ph** [comment]
@sdgun The problem is that it doesn't load. It seems like another bug with authorization (wrong HTTP request headers) that I'm currently trying to figure out.

**Comment by sdgun** [comment]
@polkovnikov-ph, At my end it is working. If you are participating to the Bug Hunt competition [Web Arena QA for 201501 Release], Post the question in the forum, http://apps.topcoder.com/forums/?module=ThreadList&forumID=592156. I think copilot can give you a direct answer.

**Comment by polkovnikov-ph** [comment]
@sdgun Nope, I'm just trying to make it work :)
I don't have a permission to the forum, so it seems I'll have to communicate with "copilot" in some other way.

**Comment by polkovnikov-ph** [comment]
@sdgun I've tried to register for that challenge and got "You cannot participate in this challenge as your country is banned". Things are getting funnier. I've never heard on any bans for Russia.

**Comment by sdgun** [comment]
I am using Chrome 40.0.2214.91 m, and using the following URL to access 'Practice Problems' : https://arena.topcoder.com/#/u/practiceProblemList.

I have no problem loading the 'Practice Problems'. 

If you are using https://qa.arena.topcoder.com/ I think it is a different build than we are using currently. So it is better to ask from the copilot, I think you can get help from these guys @skyhit, @huangqun or @mdesiderio.
