### ISSUE TITLE
Long time taken to load the problem in 'Practice Problems'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#445]
Description
-----------------------------------------------------------------
Long time taken to load the problem in 'Practice Problems'

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
Go to 'Practice Problems'
Enter : ColorfulBuilding in the Search area
Click ENTER
When the Problem displays
Click on a Problem
eg: ColorfulBuilding

Long time taken to load the problem
Also very slow when we deal with a 'Practice Problem'

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must load the 'Practice Problems'

Actual Result
-----------------------------------------------------------------
Long time taken to load the problem in 'Practice Problems'

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![11](https://cloud.githubusercontent.com/assets/4592712/5870597/15d41d6e-a2f7-11e4-8f23-7dc69a40af41.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by skyhit** [comment]
it is a known issue.

**Comment by huangqun** [comment]
@skyhit is this a server side issue or web arena issue?

**Comment by skyhit** [comment]
@huangqun  close this, we have a fix now.
