### ISSUE TITLE
[$30] Compilation pop up layout issue

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#447]
Description
-----------------------------------------------------------------
Compilation pop up layout issue

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Practice Problems'
Click 'ABCPath'

When the Problem displayed
Click Settings to change the default language to JAVA
Enter the code
Click Compile

Check the Pop up

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display the title of the compilation pop up

Actual Result
-----------------------------------------------------------------
Compilation pop up layout issue

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![21](https://cloud.githubusercontent.com/assets/4592712/5870673/229f602a-a2f8-11e4-838f-a6c08dfe318f.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
fixed
