### ISSUE TITLE
[$30] If there are only one page, no need to display pagination

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#449]
Description
-----------------------------------------------------------------
If there are only one page, no need to display pagination

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the voding phase starts
Click ENTER

Open a Problem
Click Loom Leaderboard
Click Division 11

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- If there are only one page, no need to display pagination

Actual Result
-----------------------------------------------------------------
Pagination displayed for one page also

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![23](https://cloud.githubusercontent.com/assets/4592712/5870759/66c0b94c-a2f9-11e4-8a71-491a0b28f719.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
