### ISSUE TITLE
[$30] Save button is not enabled 

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#450]
Description
-----------------------------------------------------------------
Save button is not enabled 

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the coding phase starts
Click ENTER

Open a Problem
Enter code to the coding area
Try to click Save
Initially the Save button is not enabled, and also it won't auto save the code after 30sec

But;

Open a Problem
Enter code to the coding area
Click Compile
Click Submit
Then change the code
Now you can see the Save button enabled
Now you can save the code by clicking on it
After than it is auto saved

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must enable the save button when we enter code into coding area for the first time (without compile and Submit)

Actual Result
-----------------------------------------------------------------
Save button is not enabled

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![24](https://cloud.githubusercontent.com/assets/4592712/5870781/d94768a8-a2f9-11e4-9aff-78ca046e7ea3.png)

Video
-----------------------------------------------------------------
https://drive.google.com/open?id=0B2TRwlgOU4zmVm81MkRLVFlyQXc&authuser=0 (Before Submit)
https://drive.google.com/open?id=0B2TRwlgOU4zmRWZ3Tm5qcWhuYlk&authuser=0 (After Submit)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by GSTVAC** [comment]
I can't reproduce this. The Save button is enabled as soon as I type the first char. I think it's already fixed.

**Comment by huangqun** [comment]
mark as fixed since I can't reproduce either

**Comment by larsrc** [comment]
I can reproduce this, as can my friend that I'm competing against. The workaround described in the original posting doesn't work.

It would help to have a hover title on the Save button when it's disabled saying why it's disabled - maybe it's autosaving already? Maybe you need to compile fist? 

In general, more hover titles would be good. For instance, the Submit button should explain what happens when you submit and re-submit.
