### ISSUE TITLE
When user close the problem and come again won't show 'Submit' and 'Compiled' Date/Time

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#452]
Description
-----------------------------------------------------------------
When user close the problem and come again won't show 'Submit' and 'Compiled' Date/Time

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the voding phase starts
Click ENTER

Open a Problem

Click 'Leaderboard', you can see the title
Now Enter code to the coding area
Click 'Compile'
Click 'Submit'

Click 'Back to Match'

Now open the same problem from the List
Check the 'Submit' and 'Compiled' Date/Time

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must show the 'Submit' and 'Compiled' Date/Time

Actual Result
-----------------------------------------------------------------
When user close the problem and come again won't show 'Submit' and 'Compiled' Date/Time

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![26](https://cloud.githubusercontent.com/assets/4592712/5871030/40b886d6-a2fd-11e4-9dd5-3a82cb1d0f36.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by skyhit** [comment]
this should be backend problem.
