### ISSUE TITLE
[$30] Test Report Layout issue

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#453]
Description
-----------------------------------------------------------------
Test Report Layout issue

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the coding phase starts
Click ENTER

Open a Problem

Now Enter code to the coding area
Click 'Compile'
Click 'Submit'

Click 'Test Panel'
Select All
Click Run Test

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must remove the small line below the expand/collapse icon

Actual Result
-----------------------------------------------------------------
Test Report Layout issue

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![27](https://cloud.githubusercontent.com/assets/4592712/5871117/559aa2b8-a2fe-11e4-8d46-2c3dd6a79b01.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
fixed
