### ISSUE TITLE
[$30] [Light Theme] Collapse/Expand Icon in Test Report Layout issue

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#454]
Description
-----------------------------------------------------------------
[Light Theme] Collapse/Expand Icon in Test Report Layout issue

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the voding phase starts
Click ENTER

Open a Problem
Expand the 'Coding Area'
Now Enter code to the coding area
Click 'Compile'
Click 'Submit'

Click 'Test Panel'

Check the collapse icon

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display the collapse icon when we expand the Test Panel

Actual Result
-----------------------------------------------------------------
Collapse/Expand Icon in Test Report Layout issue

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![28](https://cloud.githubusercontent.com/assets/4592712/5871167/13b6afbc-a2ff-11e4-9058-d24b4ef67fcd.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
