### ISSUE TITLE
[$25] [Orange Theme] Chat Room in coding area Layout issue

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#455]
Description
-----------------------------------------------------------------
[Orange Theme] Chat Room in coding area Layout issue

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the voding phase starts
Click ENTER

Open a Problem
Expand the 'Coding Area'
Now Enter code to the coding area
Click 'Compile'
Click 'Submit'

Click 'back to Match'

Open the same problem again

Expected Result
-----------------------------------------------------------------
Must fix the Issue.

Actual Result
-----------------------------------------------------------------
Chat Room in coding area Layout issue

Environment
-----------------------------------------------------------------
IE 11 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![29](https://cloud.githubusercontent.com/assets/4592712/5871195/6fdc7da8-a2ff-11e4-8250-66f5d770e82d.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
fixed
