### ISSUE TITLE
[$30] When user type text on the chat area, screen scrolls up

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#457]
Description
-----------------------------------------------------------------
When user type text on the chat area, screen scrolls up

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the voding phase starts
Click ENTER

Open a Problem
Enter the code
Click Compile
Click Submit

Click Chat Room 
Click Search Icon
Enter text to chat

Check the background screen

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must not have horizontal scroll bars in 'Problem Statement'

Actual Result
-----------------------------------------------------------------
'Problem Statement' have a horizontal scroll bars

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Video
-----------------------------------------------------------------
https://drive.google.com/open?id=0B2TRwlgOU4zmZzNlV2lmMXo0TUU&authuser=0

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
@huangqun can't reproduce

**Comment by huangqun** [comment]
fixed
