### ISSUE TITLE
[$30] Search: Match Case : Layout Issue when we expand the Chat Area in Code Area

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#458]
Description
-----------------------------------------------------------------
Search: Match Case : Layout Issue when we expand the Chat Area in Code Area

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the voding phase starts
Click ENTER

Open a Problem
Enter the code
Click Compile
Click Submit

Click Chat Room 
Click Search Icon

Expand the Chat area

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display the text with in the area

Actual Result
-----------------------------------------------------------------
Search: Match Case : Layout Issue when we expand the Chat Area in Code Area

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![32](https://cloud.githubusercontent.com/assets/4592712/5871543/6b7ce030-a305-11e4-93bc-bb7191f401bd.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
