### ISSUE TITLE
[$30] Room Leaderboard : Filter : Layout Issue when we expand the Room Leaderboard in Code Area

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#459]
Description
-----------------------------------------------------------------
Room Leaderboard : Filter : Layout Issue when we expand the Room Leaderboard in Code Area

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the voding phase starts
Click ENTER

Open a Problem
Enter the code
Click Compile
Click Submit

Click Room Leaderboard 
Expand the Room Leaderboard
Click Filter

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display the Filter near the drop down icon

Actual Result
-----------------------------------------------------------------
Room Leaderboard : Filter : Layout Issue when we expand the Room Leaderboard in Code Area

Environment
-----------------------------------------------------------------
Chrome 39.0.2171.95 m in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![33](https://cloud.githubusercontent.com/assets/4592712/5871624/7f027b8c-a306-11e4-9c52-fc420ef78718.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
fixed
