### ISSUE TITLE
[$30] Back button displayed when we switch between the Grid and List view

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#460]
Description
-----------------------------------------------------------------
Back button displayed when we switch between the Grid and List view

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the coding phase starts

In the 'Match Schedule '
Click Today : eg: 23rd
Click List View
Click Grid View

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must not display the Back button

Actual Result
-----------------------------------------------------------------
Back button displayed when we switch between the Grid and List view

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![34](https://cloud.githubusercontent.com/assets/4592712/5871776/8a27a8d2-a308-11e4-8363-62a2b60d856e.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by ananthhh** [comment]
I think its already fixed. Not able to reproduce

**Comment by huangqun** [comment]
not able to reproduce, marking as fixed
