### ISSUE TITLE
Chat text won't clear when the Chat [OFF] in Chat Settings

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#461]
Description
-----------------------------------------------------------------
Chat text won't clear when the Chat [OFF] in Chat Settings

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the coding phase starts
Click ENTER

In the Chat Area
Click Chat Settings --> Chat [OFF]
Enter a chat

Check the textbox

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must clear the Chat text

Actual Result
-----------------------------------------------------------------
Chat text won't clear when the Chat [OFF] in Chat Settings

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![35](https://cloud.githubusercontent.com/assets/4592712/5871946/1a2f2476-a30b-11e4-9d6b-1eeffa95eef8.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by skyhit** [comment]
this is because the chat is off.
