### ISSUE TITLE
[$25] Go to Line, won't display the line in the visible area

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#462]
Description
-----------------------------------------------------------------
Go to Line, won't display the line in the visible area

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the coding phase starts
Click ENTER
Open a Problem 
Enter a code
Click Compile and Submit

When the Challenge Phase is ON
Click on a score of another competitor
In the Coding Area [Don't expand the coding area]
Enter 35 as Go to Line
Click ENTER

Check the Last Line

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must active the cursor in the line
- Must display the line as the final line

Actual Result
-----------------------------------------------------------------
Go to Line, won't display the line in the visible area

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![36](https://cloud.githubusercontent.com/assets/4592712/5872041/78a67cd8-a30c-11e4-8539-5572b4a94923.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
@huangqun now in challenge phase it shows image of code

**Comment by huangqun** [comment]
closing this then
