### ISSUE TITLE
[$25] Full Challenge Area is not visible [No scroll bar to scroll the list]

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#463]
Description
-----------------------------------------------------------------
Full challenge Area is not visible

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the coding phase starts
Click ENTER
Open a Problem 
Enter a code
Click Compile and Submit

When the Challenge Phase is ON
Click on a score of another competitor
In the Coding Area [Don't expand the coding area]
Click 'Challenge'

***** No scroll bar to scroll the list

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display the challenge area fully
- Must have scroll bar in collapsed view

Actual Result
-----------------------------------------------------------------
Full challenge Area is not visible

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![37](https://cloud.githubusercontent.com/assets/4592712/5872097/2f5311a8-a30d-11e4-9ddc-2b2f7f313566.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by crimmc** [comment]
Working on it...

**Comment by crimmc** [comment]
This issue is the same as #517. Once that is accepted/fixed this will be fixed also.

**Comment by huangqun** [comment]
fixed
