### ISSUE TITLE
[$35] Won't do nothing when we click Search icon in Challenges Table

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#464]
Description
-----------------------------------------------------------------
Won't do nothing when we click Search icon in Challenges Table

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the coding phase starts
Wait till the Challenge Phase is ON
Click on a score of another competitor
In the Coding Area [Don't expand the coding area]
Click 'Challange'
Challenge some problems

Now go to Lobby
Click ENTER button of that Match from 'Active Matches'
Click 'Challenges & Leaderboard'
Click 'Search' icon of the Challenges table

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display coding history

Actual Result
-----------------------------------------------------------------
Won't do nothing when we click Search icon in Challenges Table

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![38](https://cloud.githubusercontent.com/assets/4592712/5872150/f6c3ad56-a30d-11e4-9993-b043ef00b580.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
fixed
