### ISSUE TITLE
[$25] [Dark Theme] Layout issue in the 'Challengers' and 'Challenges' tables

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#465]
Description
-----------------------------------------------------------------
[Dark Theme] Layout issue in the 'Challengers' and 'Challenges' tables

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the match and when the coding phase starts
Wait till the Challenge Phase is ON
Click on a score of another competitor
In the Coding Area [Don't expand the coding area]
Click 'Challange'
Challenge some problems

Now go to Lobby
Click ENTER button of that Match from 'Active Matches'
Click 'Challenges & Leaderboard'

Check the header line of the  'Challengers' and 'Challenges' tables
Compare with other themes (39.2)

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Lines must consistant

Actual Result
-----------------------------------------------------------------
Layout issue in the 'Challengers' and 'Challenges' tables

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![39 1](https://cloud.githubusercontent.com/assets/4592712/5872199/b238e150-a30e-11e4-967f-ac3178fdadeb.png)
![39 2](https://cloud.githubusercontent.com/assets/4592712/5872200/b240782a-a30e-11e4-8150-108db86a369c.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
fixed
