### ISSUE TITLE
[$25] 'Back to My Room' button displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#466]
Description
-----------------------------------------------------------------
'Back to My Room' button displayed

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'

Click ENTER from the completed Match
Disconnect the Internet
When the 'Disconnected' pop up appears 
Click OK
When the 'Reconnect' pop up appears 
Click Reconnect

Check above the score area of the table
'Back to My Room' button displayed
After while is hides

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must not show the button

Actual Result
-----------------------------------------------------------------
'Back to My Room' button displayed

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![40](https://cloud.githubusercontent.com/assets/4592712/5872503/4b2feb44-a312-11e4-9827-72216675071a.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by crimmc** [comment]
Working on it...

**Comment by crimmc** [comment]
Unfortunately, I am unable to reproduce the issue with a Firefox 35 and using the "Developer/Offline Mode" option (see attached Youtube video).

Youtube:http://youtu.be/jasEn43vPTA

**Comment by huangqun** [comment]
mark as fixed since can't reproduce
