### ISSUE TITLE
[$30] 'Coding Phase will start in: 0 seconds' displayed when we enter into Match Summary 

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#467]
Description
-----------------------------------------------------------------
'Coding Phase will start in: 0 seconds' displayed when we enter into Match Summary 

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the contest
When the Coding phase start time is less than 8 min
Click ENTER

Check the ''Coding Phase will start in: xx seconds' section [Green Box]

It will display : 'Coding Phase will start in: 0 seconds'

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must show the real remaining time

Actual Result
-----------------------------------------------------------------
'Coding Phase will start in: 0 seconds' displayed when we enter into Match Summary 

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![41](https://cloud.githubusercontent.com/assets/4592712/5872819/b53de5a6-a315-11e4-9492-500a6a7ba73d.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by crimmc** [comment]
Working on it...

**Comment by crimmc** [comment]
Unfortunately, I am unable to reproduce the issue.
On my system I'm allowed to enter with a 1 minute or less before the codding starts and the left green are displays the number of seconds till coding starts.

**Comment by GSTVAC** [comment]
I can't reproduce it either. The time is showing fine.

**Comment by huangqun** [comment]
mark as fixed and credit goes to @crimmc  for being the 1st one to report it.
