### ISSUE TITLE
[$25] System Message is not fully displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#468]
Description
-----------------------------------------------------------------
System Message is not fully displayed

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In the 'Active Matches'
Register for the contest
When the Coding phase start time is less than 8 min
Click ENTER

In the Chat Area
Enter 11 Chats (only one line)
Now Click Chat Settings;

Auto-Scrolling --> ON
Chat --> OFF

Now try to enter chat
Message is not fully displayed --> Auto scroll is not happening

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must show the full message

Actual Result
-----------------------------------------------------------------
System Message is not fully displayed

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![42](https://cloud.githubusercontent.com/assets/4592712/5873315/0926e82a-a31b-11e4-9f4c-a27232412b32.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
