### ISSUE TITLE
No copy link on the profile overview section

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#471]
Description
-----------------------------------------------------------------
No copy link on the profile overview section

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
In 'Profile Overview & Important Messages'

Check the Copy Link

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must show copy link on the profile overview section

Actual Result
-----------------------------------------------------------------
No copy link on the profile overview section

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by skyhit** [comment]
is it expected to have this copy link?  I don't remember.
