### ISSUE TITLE
Score Pop up flickers

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#472]
Description
-----------------------------------------------------------------
Score Pop up flickers

Steps
-----------------------------------------------------------------
1. Go to : http://arena.topcoder.com/
2. Login via Valid User
3. Register for a contest
4. Once the coding phase starts, click Enter
5. From the problems list given in right sidebar click the link "Unopened"
6. Once reading through the problem, click gear icon from coding area
7. Choose the language as JAVA and click OK
8. Enter your code in coding area with a missing, say "}" or ";"
9. Click Compile
10. Now click Submit and click Yes on the confirmation window
11. Correct the code and then click Compile
12. Once successfull click Submit and click Yes on the confirmation window

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must not flicker

Actual Result
-----------------------------------------------------------------
Score Pop up flickers

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Video
-----------------------------------------------------------------
https://drive.google.com/open?id=0B2TRwlgOU4zmd2FiWFAtSWlXbk0&authuser=0

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by skyhit** [comment]
the video is improper.
