### ISSUE TITLE
[$25] Test Panel just opens and gets closed immediately, when accessed after an unsuccessful compilation

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/arena-web#476]
Env: Mac OS 10.10.1 Chrome39

1. Go to arena.topcoder.com and login with valid credentials.
2. Register for an SRM contest and enter into it
3. Choose Colorful Building Problem and select C++ as language
4. Enter incorrect code and compile
5. Click Test Panel and observe

Actual:

Test Panel opens and then closes immediately.

Expected:

It should throw an error when user tries to Test after an unsuccessful compilation. It should not just open and close the popup.

Video link: https://www.dropbox.com/s/vcw62rj4mujsw3k/Arenaweb-476.mp4?dl=0

**Comment by shubhendusaurabh** [comment]
@huangqun already fixed

**Comment by huangqun** [comment]
fixed
