### ISSUE TITLE
[$30] [a4350000000CwOBAA0] - Remember me is not working

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/arena-web#480]
Env: Mac OS 10.10.1 Chrome40

1. Hit url : arena.topcoder.com
 2. Enter username and password in topcoder credentails
 3. Check the remember me checkbox and click Login
 4. Now click Logout link and close the browser/tab
 5. Open the above arena url in a new tab/window
 6. Start typing the username

Actual:
It is not remembering the matching username. 

Expected:
Arena should remember the matching username

![arena-480](https://cloud.githubusercontent.com/assets/5114190/5878859/1c5972a2-a350-11e4-9cde-7eb33f70e587.jpg)

**Comment by ananthhh** [comment]
Related to #505

**Comment by huangqun** [comment]
@ananthhh  you are right, this is not a valid case.
