### ISSUE TITLE
[a4350000000DDAlAAO] To verify browser remembers the username entered by user is 'remember me' is checked

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#481]
Description
-----------------------------------------------------------------
[a4350000000DDAlAAO] To verify browser remembers the username entered by user is 'remember me' is checked

Steps
-----------------------------------------------------------------
"1. Hit url : arena.topcoder.com
 
2. Enter the username and password
 
3. Click login
 
4. Now logout of the system and close the browser
 
5. Reopen the browser and type the username (expected 1)
 
6. Now enter the username and password, check the 'remember me' and click login
 
7. Now logout of the system and close the browser
 
8. Reopen the browser and type the username (expected 2)"

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display the records of the Division

Actual Result
-----------------------------------------------------------------
Browser won't remember the username

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 40.0.2214.91 m and FF 34.0.5 in Windows 7 Pro 64bit

Video
-----------------------------------------------------------------
https://drive.google.com/open?id=0B2TRwlgOU4zmRmdETGtZbjZPaUU&authuser=0

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by skyhit** [comment]
Must display the records of the Division?

**Comment by sdgun** [comment]
Sorry. Actual result should be : must remember the username.

**Comment by skyhit** [comment]
duplicate with #480
