### ISSUE TITLE
[Orange and Light Theme] 'Rounds' Drop down layout issue

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#483]
Description
-----------------------------------------------------------------
[Orange and Light Theme] 'Rounds' Drop down layout issue

Steps
-----------------------------------------------------------------
Go to : http://arena.topcoder.com/
Login via Valid User
Go to Orange or Light Theme
In the 'Leaderboard'
Click 'Round' drop down

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must have the bottom line

Actual Result
-----------------------------------------------------------------
'Rounds' Drop down layout issue

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 39.0.2171.95 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![7](https://cloud.githubusercontent.com/assets/4592712/5879760/eef50968-a357-11e4-9039-c6ef03a38c9d.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by huangqun** [comment]
I believe this is already fixed in dev branch
