### ISSUE TITLE
[$20] [Orange and Light Themes] Contest slider widget borders are missing

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#484]
Description
-----------------------------------------------------------------
[Orange and Light Themes] Contest slider widget borders are missing

Steps
-----------------------------------------------------------------
Hit url : arena.topcoder.com
 
Enter the username and password
 
Click login
 

Switch to Orange or Light Theme
Check the Contest slider widget borders

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display the borders

Actual Result
-----------------------------------------------------------------
Contest slider widget borders are missing

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 40.0.2214.91 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![52 1](https://cloud.githubusercontent.com/assets/4592712/5879815/7b008770-a358-11e4-9f91-f6b1b7505ff6.png)
![52](https://cloud.githubusercontent.com/assets/4592712/5879816/7b385cae-a358-11e4-9ab0-97db57d24cda.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by huangqun** [comment]
Closing this since it's the same as #487

**Comment by huangqun** [comment]
Actually, closing #487 and this is reopened

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
