### ISSUE TITLE
[$20] Border not displayed for "Challenges Floating Widget"

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/arena-web#487]
Env: Mac OS 10.10.1 Chrome40

1. Go to arena.topcoder.com and login with valid user details
2. In the Dashboard, observe the challenge floating widget in all the themes

Actual:
Border for that challenge is displayed only in dark theme. In Orange and light theme, border is not displayed.

Expected:
Border should be displayed for all the themes.

![arena-487a](https://cloud.githubusercontent.com/assets/5114190/5881264/6cb44672-a365-11e4-833b-a45235e35917.jpg)

![arena-487b](https://cloud.githubusercontent.com/assets/5114190/5881265/75db51b4-a365-11e4-8990-d5ec6bd197a4.jpg)

**Comment by skyhit** [comment]
duplicate with #484

**Comment by huangqun** [comment]
closing it since it's a duplicate
