### ISSUE TITLE
notification message text color is not good (not easy to see the text)

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/arena-web#488]
win 8, FF35
1. login to the arena
2. register for a match
3. then wait until the coding starts, observe the notification on the top right

expected: "Yes" and "No" should be changed to a proper color so that they're easily seen.

actual: see screenshot.

![h](https://cloud.githubusercontent.com/assets/4590317/5885563/facd1764-a3aa-11e4-9d3e-30bd2fb2f8b8.jpg)

**Comment by skyhit** [comment]
no change need now. it is clear.
