### ISSUE TITLE
[$25] [Orange and Light Themes] Layout issue in the Chat Settings

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#489]
Description
-----------------------------------------------------------------
[Orange and Light Themes] Layout issue in the Chat Settings

Steps
-----------------------------------------------------------------
Hit url : arena.topcoder.com
Enter the username and password
Click login
Switch to Orange or Light Theme
Click 'Chat Settings' in the Chat Area

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must have a clear container like in the Dark Theme

Actual Result
-----------------------------------------------------------------
Layout issue in the Chat Settings

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 40.0.2214.91 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![53 1](https://cloud.githubusercontent.com/assets/4592712/5885773/6bb40432-a39d-11e4-9697-f215cd13c395.png)
![53 2](https://cloud.githubusercontent.com/assets/4592712/5885774/6bb71460-a39d-11e4-8ada-0fd85f6a14e2.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by shubhendusaurabh** [comment]
will be fixed in PR #538

**Comment by huangqun** [comment]
fixed
