### ISSUE TITLE
[$30] [a41500000000lcyAAA] "The communication with the competition server has been interrupted! Please verify your network connection, copy your work, and refresh this page." is not displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#491]
Description
-----------------------------------------------------------------
[a41500000000lcyAAA] "The communication with the competition server has been interrupted! Please verify your network connection, copy your work, and refresh this page." is not displayed

Steps
-----------------------------------------------------------------
Hit url : arena.topcoder.com
Enter the username and password
Click login
Disconnect the Internet
Wait
It will show : "The connection to the server has been lost. Please log off and log in again."
Click OK

Must change this message to [a41500000000lcyAAA]: "The communication with the competition server has been interrupted! Please verify your network connection, copy your work, and refresh this page."

But it will display the old message

Connect the Internet
Now Reconnection pop up displayed after sometime

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- "The communication with the competition server has been interrupted! Please verify your network connection, copy your work, and refresh this page." must display

Actual Result
-----------------------------------------------------------------
"The communication with the competition server has been interrupted! Please verify your network connection, copy your work, and refresh this page." is not displayed

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 40.0.2214.91 m and FF 34.0.5 in Windows 7 Pro 64bit

Video
-----------------------------------------------------------------
https://drive.google.com/open?id=0B2TRwlgOU4zmSjJ5T0FQcG5mZGs&authuser=0

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by ananthhh** [comment]
Working on it

**Comment by huangqun** [comment]
fixed
