### ISSUE TITLE
[$50] [a4350000000DDEsAAO] - Auto-save does not happen

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/arena-web#492]
Env: Mac OS 10.10.1 Chrome40

1. Login to arena.topcoder.com
 2. Register and enter the coding phase
 3. Write your code
 4. Go back and come to the same coding page

Actual:

Code is not getting auto-saved

Expected:

Code should be auto-saved as per the testcase.

Video: https://www.dropbox.com/s/0256vn45o1pf427/Arena-492.mp4?dl=0

**Comment by ananthhh** [comment]
Code will be saved automatically only after specified interval. If user goes back to room before that interval, then code won't be saved.
Check this video http://goo.gl/hS3KSH

**Comment by huangqun** [comment]
not an issue
