### ISSUE TITLE
[$25] [Orange and Light Theme] "Processing System Test...' Loader is not visible

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#493]
Description
-----------------------------------------------------------------
[Orange and Light Theme] "Processing System Test...' Loader is not visible

Steps
-----------------------------------------------------------------
Hit url : arena.topcoder.com
 
Enter the username and password
 
Click login
 

Click 'Practice Problem'
Open a problem
Enter code
Click Compile
Click Submit

Now click Run System Tests
Check the loader

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- "Processing System Test...' Loader must clearly visible

Actual Result
-----------------------------------------------------------------
"Processing System Test...' Loader is not visible

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 40.0.2214.91 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![55](https://cloud.githubusercontent.com/assets/4592712/5886253/c3d6437a-a3b9-11e4-84a7-a1a08ff02355.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
