### ISSUE TITLE
[$30] 'Run System Tests' disabled when we expand the Coding Area

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#494]
Description
-----------------------------------------------------------------
'Run System Tests' disabled when we expand the Coding Area

Steps
-----------------------------------------------------------------
Hit url : arena.topcoder.com
Enter the username and password
Click login

Click 'Practice Problem'
Open a problem
Enter code
Click Compile
Click Submit

Now Check the  'Run System Tests'  --> Enable
Expand the Coding Area
Now Check the  'Run System Tests'  --> Disable

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- 'Run System Tests' must not disable

Actual Result
-----------------------------------------------------------------
'Run System Tests' disabled when we expand the Coding Area

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 40.0.2214.91 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![56](https://cloud.githubusercontent.com/assets/4592712/5886258/32da62f6-a3ba-11e4-9d0f-cdecf24ad64f.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by crimmc** [comment]
Working on it...

**Comment by huangqun** [comment]
fixed
