### ISSUE TITLE
Match Schedule - Full list of matches not displayed when a day has more matches

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/arena-web#495]
![arena-495](https://cloud.githubusercontent.com/assets/5114190/5886321/cdb9026a-a3be-11e4-939d-094f5cb31e52.jpg)
Env: Mac OS 10.10.1 Chrome40

1. Go to arena.topcoder.com and login with valid user details
2. In the Match Schedule Widget, hover over the date Jan 23
3. Observe the popup

Actual:

Popup Does not display all the matches. Please see screensho.

Expected:

Popup should be positioned such that its completely visible within the screen.

**Comment by skyhit** [comment]
duplicated.
