### ISSUE TITLE
[$30] Chat Settings: Not able to scroll till the end

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/arena-web#496]
Env: Mac OS10.10.1 Chrome40

1. Go to arena.topcoder.com and login with valid credentials
2. Register for any contest and Enter into it
3. Open any problem and open the chat settings widget 
4. Select Reply To or Whisper and observe the values of the second drop down

Actual:

Values of the second drop down are not displayed within the screen and hence not able to select any values other than the first one.

Expected:

1. Dropdown values should be visible
2. User should be able to select all the values of the dropdown.

Video Link: https://www.dropbox.com/s/jv1jl0gbiqpdycv/arena-496.mp4?dl=0

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
