### ISSUE TITLE
[$25] 'Back to My Room' button layout issue

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#497]
Description
-----------------------------------------------------------------
'Back to My Room' button layout issue

Steps
-----------------------------------------------------------------
Hit url : arena.topcoder.com
Enter the username and password
Click login
In the 'Active Matches'
Click ENTER on a Match that you haven't registered
Check the 'Back to My Room' button in the Match Summary

Click on the 'Back to My Room' won't happen anything

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must not touch the top border

Actual Result
-----------------------------------------------------------------
'Back to My Room' button layout issue

Environment
-----------------------------------------------------------------
Chrome 40.0.2214.91 m  in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![57](https://cloud.githubusercontent.com/assets/4592712/5886583/f4881c92-a3cc-11e4-85ba-160513d6f56e.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by ananthhh** [comment]
Fixed it already

**Comment by huangqun** [comment]
fixed

**Comment by huangqun** [comment]
@ananthhh I think your fix introduced a new bug, see below the "Enter" icon is overlapping with the table, please fix it:

![snip20150205_2](https://cloud.githubusercontent.com/assets/6045894/6054913/7cabddf0-ad2f-11e4-82d4-e1ef8b444481.png)

**Comment by ananthhh** [comment]
Fixed!

**Comment by huangqun** [comment]
fixed
