### ISSUE TITLE
[$25] Problem Status is wrong if we won't register to the contes

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/arena-web#498]
Description
-----------------------------------------------------------------
Problem Status is wrong if we won't register to the contest

Steps
-----------------------------------------------------------------
Hit url : arena.topcoder.com
Enter the username and password

Click login

When the coding phase is ON

In the 'Active Matches'
Click ENTER on a Match that you haven't registered
Check the 'Match Status' section

Expected Result
-----------------------------------------------------------------
Must fix the Issue.
- Must display : Unopened

Actual Result
-----------------------------------------------------------------
Open

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 40.0.2214.91 m and FF 34.0.5 in Windows 7 Pro 64bit

Image
-----------------------------------------------------------------
![58](https://cloud.githubusercontent.com/assets/4592712/5886601/a85efcc2-a3cd-11e4-9454-ec3da5f20a4a.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201501 Release

**Comment by ananthhh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
