### ISSUE TITLE
[$25] Chat Widget: Settings Gear icon is not working in full screen mode

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/arena-web#499]
Env: Mac OS10.10.1 Chrome40

Go to arena.topcoder.com and login with valid credentials
Register for any contest and Enter into it
Open any problem and open the chat settings widget
Click full screen icon and then click Settings icon

Actual:

Settings icon is not working

Expected:

Settings icon should work in full screen too.
![arena-499](https://cloud.githubusercontent.com/assets/5114190/5886610/2ca68c66-a3ce-11e4-8947-cd22b63422b1.jpg)

**Comment by ananthhh** [comment]
It is working.
![image](https://cloud.githubusercontent.com/assets/3583234/6028077/b67dbcac-ac0c-11e4-88c8-7852e59042c4.png)

**Comment by huangqun** [comment]
@ananthhh can you fix this UI issue for additional payment? This happens in both light and orange theme.
![snip20150204_1](https://cloud.githubusercontent.com/assets/6045894/6040336/a0b86f30-acab-11e4-8528-d4e88bdf3ad0.png)

**Comment by huangqun** [comment]
@ananthhh ignore my previous comment, this one is being handled in another issue.
