### ISSUE TITLE
[$30] Chat Widget: Coder info is not staying in screen. It just opens and then closes

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/arena-web#500]
Env: Mac OS10.10.1 Chrome40

Go to arena.topcoder.com and login with valid credentials
Register for any contest and Enter into it
Open any problem and open the chat settings widget
Click on any handle name from Who's here section and observe

Actual:

Coder info popup opens and then closes immediately.

Note: This issue does not occur in the Main Chat area.

Expected:

It should stay on screen until user closes it manuallly.

Video Link: https://www.dropbox.com/s/maxhyr89r8tf28e/Arena-500.mp4?dl=0

**Comment by shubhendusaurabh** [comment]
working on it

**Comment by GSTVAC** [comment]
working

**Comment by GSTVAC** [comment]
Done.

**Comment by huangqun** [comment]
fixed
