### ISSUE TITLE
Leaderboard Widget: Last row is empty in Division II

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/arena-web#501]
Env: Mac OS10.10.1 Chrome40

Go to arena.topcoder.com and login with valid credentials
Register for any contest and Enter into it
Open any problem and open the Leaderboard widget
Click Division II and observe the last row

Actual:

Last row is empty and unnecessary.

Expected:

There should not be empty row
![arena-501](https://cloud.githubusercontent.com/assets/5114190/5886686/2738d262-a3d2-11e4-9938-6801686b8130.jpg)

**Comment by skyhit** [comment]
this is pagination, we should hide it if there is no pagination. but it is already reported.
