### ISSUE TITLE
Room Leaderboard: Radio buttons are not visible in Orange and Dark theme

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/arena-web#502]
Env: Mac OS10.10.1 Chrome40

Go to arena.topcoder.com and login with valid credentials
Register for any contest and Enter into it
Open any problem and open the Room Leaderboard Widget
Observe the radio button Status and Points in all the 3 themes

Actual:
Only in Light Theme, Radio button is visible. In dark and light them, radio button is not visible

Expected:

Radio button should be visible in all the themes.

![arena-502](https://cloud.githubusercontent.com/assets/5114190/5886716/b84a0540-a3d3-11e4-87cb-c736b4c0b673.jpg)

![arena-502b](https://cloud.githubusercontent.com/assets/5114190/5886717/c18a426e-a3d3-11e4-9fe3-b1d03e817641.jpg)

![arena-502c](https://cloud.githubusercontent.com/assets/5114190/5886724/c9826bae-a3d3-11e4-8cf3-9e8a390bd65c.jpg)

**Comment by skyhit** [comment]
the color is light, but it is present.
