### ISSUE TITLE
[$30] No proper message displayed if compiling the code after coding phase ended

### ISSUE THREAD

**Issue by winterflame** [appirio-tech/arena-web#503]
1. login, register for a match
2. enter solution for a problem, then wait for the coding phase ends
3. click Compile button, observe

expected: it should display some text like "You cannot compile after the coding phase ended."

actual: it will display a modal window "Please wait for compiling results.", see screenshot.

![qq20150124-3](https://cloud.githubusercontent.com/assets/4590317/5886920/bb6d2dc0-a3f0-11e4-9606-d44907a0f65a.jpg)

**Comment by ananthhh** [comment]
working on it

**Comment by huangqun** [comment]
fixed
