### ISSUE TITLE
[$25] No scrollbar for test panel in split view

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#517]
No scrollbar for test panel in split view

![screenshot from 2015-01-29 15 22 14](https://cloud.githubusercontent.com/assets/1629884/5966511/b6435a1c-a7ca-11e4-8e91-95c90e8ce884.png)

**Comment by mdesiderio** [comment]
@huangqun bug bounty

**Comment by GSTVAC** [comment]
working

**Comment by crimmc** [comment]
Working on it...

**Comment by huangqun** [comment]
fixed
