### ISSUE TITLE
[$30] 'Test Report' Error messages are not fully displayed

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#61]
_From @sdgun on November 25, 2014 7:36_

Description
-----------------------------------------------------------------
'Test Report' Error messages are not fully displayed

Steps
-----------------------------------------------------------------
Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
When the Coding Phase is ON
Click ENTER
Open a Problem
In the Coding area enter some code
Click compile and Submit
NOTE: Enter some incorrect codings also
Now click 'Test Panel'
Seelct All
Click Run Test

Scroll down and check the Errors

Expected result
-----------------------------------------------------------------
Must fix the Issue
- Must display them fully, currently some parts are hidden by the scroll bars and
- Some of them goes out of the container

Actual result
-----------------------------------------------------------------
'Test Report' Error messages are not fully displayed

Image
-----------------------------------------------------------------
![26](https://cloud.githubusercontent.com/assets/4592712/5179461/686f2262-74a3-11e4-8665-8b07b0b863d4.png)

Environment
-----------------------------------------------------------------
IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201411 Release

_Copied from original issue: cloudspokes/arena-web#1042_

**Comment by huangqun** [comment]
fixed
