### ISSUE TITLE
The arena shows only 12 problems in the "Practice Problems" tag

### ISSUE THREAD

**Issue by rahulkhairwar** [appirio-tech/arena-web#663]

**Comment by exphys2001** [comment]
ditto. there used to be hundreds of problems, now only 12.

**Comment by exphys2001** [comment]
Fixed! Thanks!

**Comment by skyhit** [comment]
@exphys2001 mainly during a SRM, in order to reduce the resource used by practice problems, the number of pratice problems will be reduced.

**Comment by square1001** [comment]
So closing issue is better.
