### ISSUE TITLE
[$50] Empty 'Problem Area' displayed when we expand it and then collapse it

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#67]
_From @mdesiderio on October 29, 2014 16:19_

1. Hit topcoder QA arena url 
2. Login through valid user 
3. Register for a contest 
4. Enter the coding phase and open a problem 
5. Scroll to the bottom of problem area 
6. Then expand and collapse the problem area

_Copied from original issue: cloudspokes/arena-web#957_

**Comment by GSTVAC** [comment]
working

**Comment by GSTVAC** [comment]
fixed #67
already fixed on 2785cc84ed5b4798a28756576a2d107f4a50c94d

**Comment by huangqun** [comment]
fixed
