### ISSUE TITLE
string::substr output is weird

### ISSUE THREAD

**Issue by eudaemon** [appirio-tech/arena-web#674]
Hi,

Somehow, string::substr output is weird.
Try https://arena.topcoder.com/#/u/practiceCode/1349/2185/2358/1/1349
Hawaiian C++ practice with the following code.

```
#include <vector>
#include <string>
#include <cstring>
#include <iostream>

#define NON_HAWAIIAN    "qrtysdfgjzxcvb"
using namespace std;
class Hawaiian
{
public:
    vector <string> getWords(string sentence);
};

vector <string> Hawaiian::getWords(string sentence)
{
    vector<string> result;

    // TODO: First tokenize the string.
    size_t foundPrev = 0;
    string delimiter = " ";
    for (;;)
    {
        size_t foundNext = sentence.find(delimiter, foundPrev);
        if (foundNext == string::npos)
            break;
        string token = sentence.substr(foundPrev, foundNext);
        cout << "foundPrev = " << foundPrev << ", foundNext = " << foundNext << ", token = " << token << " |endl| ";
        // cout << token << "|endl|";
        char *hawaii_filter = strtok((char*)token.c_str(), NON_HAWAIIAN);
        if (hawaii_filter) {
            // Do nothing
        } else {
            result.push_back(token);
        }
        foundPrev = foundNext + 1;
    }

    return result;
}
```

This is the input
Test Case 1 : Hawaii is an island

This is the output.
Standard Output: foundPrev = 0, foundNext = 6, token = Hawaii |endl| foundPrev = 7, foundNext = 9, token = is an isl |endl| foundPrev = 10, foundNext = 12, token = an island |endl|

The output token value of "sentence.substr(7, 9)" should be "is" not "is an isl".
The null termination did not seemed to work well.

Thanks,

**Comment by square1001** [comment]
It's not a topcoder compiler bug.
substr(a, b) is the length-b string from position a.
So you should close the issue.

**Comment by eudaemon** [comment]
Ah. Yes. My bad. You are right about substr(a,b) where b is not the end index but the length.
Sorry.
