### ISSUE TITLE
Practice problems in Arena always in New status

### ISSUE THREAD

**Issue by sahilpalvia** [appirio-tech/arena-web#687]
The practice problems in the arena are always in the 'New' status even after submitting the answer. The submission shows a score inside the problem but on the landing page of the practice problems the status and the score are never updated.

![screen shot 2016-08-09 at 6 56 33 pm](https://cloud.githubusercontent.com/assets/6037597/17536470/20febc48-5e63-11e6-9750-6d5a036eed4d.png)

**Comment by AmbroseChase** [comment]
Same issue here. It's strange.

I heard that Top Coder was a good website, but your issue has some much time as opened. And now I have the same problem.

Disappointing.
