### ISSUE TITLE
Is there any C compiler to practice

### ISSUE THREAD

**Issue by anilthedreamer** [appirio-tech/arena-web#688]
Dear TopCoder,

I write code in C only, I want to practice problem.
Could you please tell where I write my program and start practicing ?

Thanks
Anil Sahu

**Comment by jeffswt** [comment]
@anilthedreamer If you really want to practice coding in C, there are a few sites you can try out:

 1. [BZ Online Judge](http://www.lydsy.com/JudgeOnline), in Chinese, but it provides a lot of nice problems.
 2. [PKU Online Judge](http://poj.org/), maintained by Peking University.
 3. [Codeforces](http://www.codeforces.com/), a Russian site.
 4. [BestCoder](http://bestcoder.hdu.edu.cn/), a Chinese site, but offers problems in English.

The best way is to migrate your coding styles to C++. Don't worry, C++ won't cause you a lot of problems, even though you commit your C code into C++ compilers they won't report a lot of Compile Errors. The main differences are the headers.

And by the way, C is no longer supported by many international and national competitions.

**Comment by jeffswt** [comment]
And I suggest you close this issue. You are posting into the wrong place.

**Comment by square1001** [comment]
Why don't you close the issue?
