### ISSUE TITLE
My Points are not shown in my dashboard

### ISSUE THREAD

**Issue by Shrutichhatbar** [appirio-tech/arena-web#696]

**Comment by Shrutichhatbar** [comment]
I submitted the code it shows I scored x points but my I check dashboard My Points column is empty

**Comment by jeffswt** [comment]
I think you are not submitting it in the contests. But the issue also applies to me.

**Comment by jeffswt** [comment]
Duplicate issue with #687.

**Comment by square1001** [comment]
Duplicate of #624 
Please close this issue because duplicated one is not very helpful.
