### ISSUE TITLE
Status of solved problems won't update

### ISSUE THREAD

**Issue by bovin-a** [appirio-tech/arena-web#717]
Hi! I'm new on arena. I solved "AB" problem from "Practice Problems" section. Here screenshot that tests passed successfully:
![](http://joxi.ru/V2VLwGWIxGR10r.jpg)

But in "Problems List" this problem still shows as "New":
![](http://joxi.ru/D2PYw6lipWyMqA.jpg)

It's right behavior or it's something like a bug?

**Comment by yurann** [comment]
I get the same response. I am sure it is a bug. 
Solved problems do not update and do not filter either.

**Comment by adriannasui** [comment]
same problem here

**Comment by square1001** [comment]
Duplicate of #712

**Comment by bovin-a** [comment]
@square1001 Thanks, i close this issue then.
