### ISSUE TITLE
I have successfully submitted 2 codings and got 350 points. But it doesnot shows the points as result.Only shows 0 points

### ISSUE THREAD

**Issue by ganesha007** [appirio-tech/arena-web#726]

**Comment by square1001** [comment]
Okay so your code failed in challenge phase or final test. So your code is wrong. If your code turned out to be failed, your score of this problem will be zero. Right?

**Comment by ganesha007** [comment]
Yes. But why 350 points shown earlier??

**Comment by square1001** [comment]
That's a topcoder rule. Though, it's not a final score. It's a "preliminary" score. Got it?

**Comment by ganesha007** [comment]
Yes. I got it. Thank you for your reply.
If you don't mind, will you please send me all the rules for topcoder.

**Comment by square1001** [comment]
You can check it on Internet - did you google it?

**Comment by ganesha007** [comment]
Yes. Just now i had google it. I got it. Thank you.

**Comment by square1001** [comment]
And it's not an issue - you can close the issue now.

**Comment by ganesha007** [comment]
Ok. Will you please send me the link where i can close the issue.
Sorry for inconvenience.

**Comment by square1001** [comment]
If you search on the Internet, you can see - https://stackoverflow.com/questions/34010565/how-do-i-close-a-github-issue-without-making-a-commit
