### ISSUE TITLE
New/Viewed/Solved status freezes at New

### ISSUE THREAD

**Issue by b0w1d** [appirio-tech/arena-web#734]
Regardless of having viewed and solved ( passed system tests ), when searching via "Practice Problems", the status remains "New".

**Comment by ssehoony** [comment]
This bug happen to me, too.

**Comment by Stevenchen77** [comment]
same bug

**Comment by Anton-Velikodnyy** [comment]
Same thing here

**Comment by square1001** [comment]
Duplicate of #717

**Comment by serge-alexandre** [comment]
same here
