### ISSUE TITLE
Not able to see Register button before the start of SRM 

### ISSUE THREAD

**Issue by Kavit900** [appirio-tech/arena-web#737]
I am registered and logged inside the topcoder arena but I don't see any register button before the start of SRM 716 and when I navigate to practice problems, I see only 12 problems and not all the list of problems.

**Comment by square1001** [comment]
Okay, "before start of SRM" means ">4 hours before SRM, or <5 minutes before SRM", right? If so, it's not a bug.
And few hours (sometimes 10~15 hours) before contest, is only able to practice about 12 problems. It's not a bug.

**Comment by Kavit900** [comment]
Ya my bad @square1001 let me close the issue and thanks for your help, appreciate it :)
