### ISSUE TITLE
Picture Not Working

### ISSUE THREAD

**Issue by jamesjpk123** [appirio-tech/arena-web#742]
URL: https://arena.topcoder.com/#/u/dashboard
Under the section "Profile Overview & Important Messages" a picture is broken, and only has alt text of my name. Here is some relevant information:

- Account made less than 20 mins ago
- Image src = https://apps.topcoder.comhttps//topcoder-prod-media.s3.amazonaws.com/member/profile/jamesjpk123-1500500077113.jpeg
- Image src leads to a DNS_PROBE_FINISHED_NXDOMAIN error in Chrome.

**Comment by square1001** [comment]
Duplicate of #680

**Comment by jamesjpk123** [comment]
Since this is a duplicate of #680, like @square1001 said, I'll close.
