### ISSUE TITLE
Only see twelve practice problems in Arena

### ISSUE THREAD

**Issue by armanraina** [appirio-tech/arena-web#743]
Hi, when I click on practice problems, I can only see twelve of them. 
![image](https://user-images.githubusercontent.com/13897679/28745790-95bf5afa-7434-11e7-8776-ce154e3583a6.png)

**Comment by square1001** [comment]
It's not a bug if algorithm contest started in only few hours (sometimes 10~15 hours) later.
Before the algorithm contest, topcoder only enables about 12 problems to practice.

**Comment by square1001** [comment]
If it's true, you can close this issue.
