### ISSUE TITLE
Practice Problem BinaryCode takes over 2 minutes to load.

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#8]
_From @Goodwine on November 29, 2014 14:10_

The problem BinaryCode is taking way too long to load, I tried the other problems, and I don't see an issue with them.
I pinpointed the issue by profiling the JS code, and it showed that the function `updateCoderPlacement` in resolvers.js is causing the bottleneck.

this is how the code looks like:
```javascript
updateCoderPlacement = function (coders) {
   coders.forEach(function (item) {
        item.roomPlace = 1;
        coders.forEach(function (other) {
            if (item.userName !== other.userName && item.totalPoints < other.totalPoints) {
                item.roomPlace += 1;
            }
        });
    });
};
```

This is the bottleneck. If I'm not wrong, this solution is bubbling down every coder according to their points. BinaryCode has 34760 coders, and the function takes 1.4 ~ 2.1 minutes, which is the result of a O(n<sup>2</sup>) bubbling algorithm.

_Copied from original issue: cloudspokes/arena-web#1099_

**Comment by mdesiderio** [comment]
@skyhit is this complete? can we close it?

**Comment by skyhit** [comment]
@mdesiderio  it is a specific problem in production, can we merge the change and test in QA or production ?

**Comment by mdesiderio** [comment]
In which branch is the code? I can certainly load it in QA, no problem.

If it was in dev last week, it is already deployed to QA.

**Comment by skyhit** [comment]
@mdesiderio  the change can be found from this pull request - https://github.com/appirio-tech/arena-web/pull/333

**Comment by mdesiderio** [comment]
@skyhit the solution in the pull request looks solid, I tested it in QA. The current code in DEV causes the browser tab to freeze completely, but the code in this pull request allows me to load the problem in just a few seconds.

I have rolled it back to the latest dev code BTW.

Is there a reason why this has not yet been merged to dev? Any other regression issues that we need to review / test before doing so?

Thanks!

**Comment by skyhit** [comment]
it is not merged to dev, because we didn't test it, since you have test it in QA env, I think it is good to merge.

**Comment by mdesiderio** [comment]
@skyhit ok, please merge.

**Comment by skyhit** [comment]
@mdesiderio  merged.
