### ISSUE TITLE
Python str.lower() built-in method bug

### ISSUE THREAD

**Issue by 3la5t1c81rdy** [appirio-tech/arena-web#835]
So, simply the str.lower() converts all components of str into lowercase letters, such as 
print("AbcDe fGHi".lower()) in python would execute as 
abcde fghi

And this function works on TopCoder Arena. However, the 'change to lowercase' applies globally somehow. (i don't know if 'globally' is even a right word to use so giving example)

So suppose writing code something like

```
(0) *class and def the module*
1 A=["Hello", "mY nAME iS", "PoTaTo"]
2 ACopy=A
3 for i in range(len(A)):
4     A[i]=A[i].lower
5 print(A)
6 print(ACopy)
```
... and when I compile and test with random example I create, it should print
>['hello', 'my name is', 'potato']
>['Hello', 'mY nAME iS', 'PoTaTo']

but instead it prints

>['hello', 'my name is', 'potato']
>['hello', 'my name is', 'potato']

I suppose it is a TopCoder-side issue, because on any other IDE and compiler I tried prints what I said 'should print'.
Thanks for reading, have a good day!

**Comment by 3la5t1c81rdy** [comment]
I found this in practice 'Aaagmnrs'

**Comment by agorbunovs** [comment]
You are not copying the A list, but rather copying a reference to A into ACopy. Then all the changes to A are reflected in ACopy. They refer to the same object. You can use `ACopy=A[:]` to do a shallow copy of A.

**Comment by 3la5t1c81rdy** [comment]
Ah. Did not know about that one. Never thought the list acts differently than integers/strings. Thanks for info!
