### ISSUE TITLE
[$30] [Common] Filter section overlap with the Top Menu section when we scroll up

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#86]
_From @sdgun on November 25, 2014 5:10_

Description
-----------------------------------------------------------------
[Common] Filter section overlap with the Top Menu section when we scroll up

Steps
-----------------------------------------------------------------
Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
Click 'ENTER' from the 'Active Matches'
Now click 'Challenges & Leaderboard'
Expand any table from 'Summary'
Click on Filter
Scroll up

Expected result
-----------------------------------------------------------------
Must fix the Issue
- Must not overlap

Actual result
-----------------------------------------------------------------
[Common] Filter section overlap with the Top Menu section when we scroll up

Image
-----------------------------------------------------------------
![4](https://cloud.githubusercontent.com/assets/4592712/5178337/ffdfb242-748f-11e4-9352-154d34796a7b.png)

Environment
-----------------------------------------------------------------
IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201411 Release

_Copied from original issue: cloudspokes/arena-web#1020_

**Comment by GSTVAC** [comment]
@huangqun I can reproduce it too. I'm using Firefox 34.0.5. Will @Helstein's submission be accepted? Can I work on it?

**Comment by huangqun** [comment]
@GSTVAC Could you let me know on which OS did you reproduce this? I'm using Mac and I can never reproduce it. Do you think you can create a screencast to show it? Thanks!

**Comment by mdesiderio** [comment]
@huangqun any updates on this issue?

**Comment by huangqun** [comment]
@GSTVAC Did you get a chance to re-test this? I think this one is fixed now.

**Comment by GSTVAC** [comment]
@huangqun Yes, it's fixed now.

**Comment by huangqun** [comment]
fixed
