### ISSUE TITLE
[$30] [Common] 'Not Assigned' pop up model is not aligned properly

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#87]
_From @sdgun on November 25, 2014 5:27_

Description
-----------------------------------------------------------------
[Common] 'Not Assigned' pop up model is not aligned properly

Steps
-----------------------------------------------------------------
Open the Web Arena URL: https://arena.topcoder.com/
Login as valid user
In the 'Dashboard'
Click 'ENTER' from the Active Matches
NOTE: Must not registered member of it

When the coding phase is ON
Try to Open a Problem

Check the model

Expected result
-----------------------------------------------------------------
Must fix the Issue
- Must center aligned

Actual result
-----------------------------------------------------------------
'Not Assigned' pop up model is not aligned properly

Image
-----------------------------------------------------------------
![10](https://cloud.githubusercontent.com/assets/4592712/5178434/d2271bfe-7491-11e4-9266-600f36a369e8.png)

Environment
-----------------------------------------------------------------
IE 10,11, Chrome 39.0.2171.65 m, FF 33.1.1 and Safari 5.1.7 in Windows 7 Pro 64bit

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201411 Release

_Copied from original issue: cloudspokes/arena-web#1026_

**Comment by GSTVAC** [comment]
working

**Comment by GSTVAC** [comment]
done

**Comment by huangqun** [comment]
fixed
