### ISSUE TITLE
[Common] When we try to scroll using the scroll bar in Chat window, Drop down closed automatically

### ISSUE THREAD

**Issue by mdesiderio** [appirio-tech/arena-web#97]
_From @sdgun on October 20, 2014 21:37_

Description
-----------------------------------------------------------------
[Common] When we try to scroll using the scroll bar in Chat window, Drop down closed automatically

Steps
-----------------------------------------------------------------
Go to : http://qa.arena.topcoder.com/#/u/dashboard
Login as Valid user
Select a Match
http://qa.arena.topcoder.com/#/u/contests/16248/
Click ENTER
Go to Chat Window
Click the Drop down (Question, Admins, General, Me etc...)
Try to scroll the list

Expected Result
-----------------------------------------------------------------
Must fix the Issue, 
- Must not close the Drop down

Actual Result
-----------------------------------------------------------------
[Common] When we try to scroll using the scroll bar in Chat window, Drop down closed automatically

Environment
-----------------------------------------------------------------
IE 11, Safari 5.1.7, Chrome 37.0.2062.102 m and FF 33 in Windows 7

Image
-----------------------------------------------------------------
![46](https://cloud.githubusercontent.com/assets/4592712/4709655/31ff35d2-58a1-11e4-891a-b9834eeee649.png)

Bug Hunt
-----------------------------------------------------------------
Web Arena QA for 201410 Release

_Copied from original issue: cloudspokes/arena-web#881_

**Comment by huangqun** [comment]
fixed already
